# Generated by Django 4.0.7 on 2022-08-12 02:49

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0003_alter_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.fields.StreamField([('title_and_text', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='your title', required=True)), ('text', wagtail.blocks.TextBlock(help_text='additional text', required=False))])), ('full_richText', streams.blocks.RichTextBlock())], blank=True, null=True, use_json_field=None),
        ),
    ]
